### ISSUE TITLE
App fails to install

### ISSUE THREAD

**Issue by limadelta26** [Alex313031/Thorium-Android#34]
**System Details**
 - OS: Android 10QP1A.190711.020 / MIUI Global 12.0.23(QCRMIXM) Stable (Xiaomi Redmi 9c)
 - Thorium Version: M117.0.5938.154 - 3rd release (latest as of 13/11/2023)

**Problem**
Not sure what the exact issue is. The app fails to install at all. File manager permissions are set correct (install from unknown sources, etc)

**Screenshots**
![WhatsApp Image 2023-11-13 at 10 42 06](https://github.com/Alex313031/Thorium-Android/assets/150660221/bdf8b921-84c2-4738-a684-e2e7673359b7)
![WhatsApp Image 2023-11-13 at 10 41 54](https://github.com/Alex313031/Thorium-Android/assets/150660221/30e3cc5e-ea60-405d-ad02-473d5fa7b37b)

**Additional Notes**
I can install the SystemWebView application fine. The Thorium shell application does the same as above (installing.... application failed to install)

I'm trying to install the arm64.apk files

System spec as follows:
CPU: 12 nm FinFET, Up to 2.0 GHz; 2 ARM Cortex A75 + 6 ARM Cortex A55, Octa-core
ARMv8.1-A

**Comment by gz83** [comment]
I can't reproduce the problem you're experiencing, so I suggest you check your phone's settings or try installing only the public_apk

**Comment by limadelta26** [comment]
I have been trying the public_arm64.apk file. 

Very weird issue. The device is 64 bit but i have managed to install the 32 bit version (of course removed the SystemWebView64 then reinstalled the 32 bit)

Not sure if this helps you or if will help others with Xiaomi devices

**Comment by ChuckBartowski91** [comment]
Doesn't install for me too on some devices, specifically huawei y6 2018 (android 8) and zte vfd 600 (android 6). I thought that the android version was too old but I managed to install thorium on android TV 7.0. 

I remember that I had the same problem on my first phone xiaomi 11 lite 5g ne (android 13) but after some days I redownloaded it and installed without problems.
I checked with droid info if I was installing the correct arm32 or arm64 version.

Quick edit: installed the arm32 version on android 8 huawei phone (droid info says it's arm64).

**Comment by x012** [comment]
I have this on my xiamoi redmi 7a when I try to install through adb:
```
$ adb install Thorium_Public_arm64.apk
Performing Streamed Install
adb: failed to install Thorium_Public_arm64.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

what i get if I try to specify the ABI:

```
$ adb install --abi arm64-v8a Thorium_Public_arm64.apk
Performing Streamed Install
adb: failed to install Thorium_Public_arm64.apk: 
Exception occurred while executing:
java.lang.IllegalArgumentException: ABI arm64-v8a not supported on this device
	at com.android.server.pm.PackageManagerShellCommand.checkAbiArgument(PackageManagerShellCommand.java:2693)
	at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:2452)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1057)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
	at android.os.ShellCommand.exec(ShellCommand.java:111)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22444)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4882)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4104)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```

when i checked it seemed like the redmi 7a has a arm64-v8a, so I don't understand what is the problem here

**Comment by gz83** [comment]
> I have this on my xiamoi redmi 7a when I try to install through adb:
> 
> ```
> $ adb install Thorium_Public_arm64.apk
> Performing Streamed Install
> adb: failed to install Thorium_Public_arm64.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
> ```
> 
> what i get if I try to specify the ABI:
> 
> ```
> $ adb install --abi arm64-v8a Thorium_Public_arm64.apk
> Performing Streamed Install
> adb: failed to install Thorium_Public_arm64.apk: 
> Exception occurred while executing:
> java.lang.IllegalArgumentException: ABI arm64-v8a not supported on this device
> 	at com.android.server.pm.PackageManagerShellCommand.checkAbiArgument(PackageManagerShellCommand.java:2693)
> 	at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:2452)
> 	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1057)
> 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
> 	at android.os.ShellCommand.exec(ShellCommand.java:111)
> 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22444)
> 	at android.os.Binder.shellCommand(Binder.java:881)
> 	at android.os.Binder.onTransact(Binder.java:765)
> 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4882)
> 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4104)
> 	at android.os.Binder.execTransactInternal(Binder.java:1021)
> 	at android.os.Binder.execTransact(Binder.java:994)
> ```
> 
> when i checked it seemed like the redmi 7a has a arm64-v8a, so I don't understand what is the problem here

It seems that your processor does not support some of the compilation optimization parameters we are currently using. It is recommended that you try to install the arm32 version.

In addition, please also ensure that the system you are using is Android 8.0 and above.

@x012

**Comment by x012** [comment]
```
$ adb shell getprop | grep abi
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
```
that's strange the v8a is not even listed here and the abilist64 is comletely empty... I didn't think that the xiaomi redmi 7a is that old to be 32 bit or I don't really know what this means...

Android vesion is '10 QKQ1.191014.001' so that shouldnt be a problem

The 32 bit version installs without any problems. But now i've run into a different one (Issue: #37 But that's a different story..)

**Comment by gz83** [comment]
> ```
> $ adb shell getprop | grep abi
> [ro.product.cpu.abi]: [armeabi-v7a]
> [ro.product.cpu.abi2]: [armeabi]
> [ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
> [ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
> [ro.product.cpu.abilist64]: []
> ```
> 
> that's strange the v8a is not even listed here and the abilist64 is comletely empty... I didn't think that the xiaomi redmi 7a is that old to be 32 bit or I don't really know what this means...
> 
> Android vesion is '10 QKQ1.191014.001' so that shouldnt be a problem
> 
> The 32 bit version installs without any problems. But now i've run into a different one (Issue: #37 But that's a different story..)

This is a restriction imposed by Google on third-party Android browsers, which requires third parties themselves (including Thorium) to find corresponding solutions. These solutions will inevitably cost money and time.

@x012

**Comment by x012** [comment]
I flashed lineage os 21 (21-20240315-NIGHTLY-Mi439) and suddenly the 'arm64-v8a' abis appeared and I could install the 64bit version of Thorium without problems. 

```
$ adb shell getprop | grep abi
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.system.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.system.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.system.product.cpu.abilist64]: [arm64-v8a]
[ro.vendor.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.vendor.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.vendor.product.cpu.abilist64]: [arm64-v8a]
```

I'm posting this because op was also a MIUI user. and there might be something fishy going on with the MIUI rom instead of cpu problems. (Unfortunately I failed to write down my exact MIUI version before i changed it). When I tried to install from the apk copied to the device i got the exact result op did, thats why I used adb to get some more info.
