### ISSUE TITLE
M126 still crash when opening. Is the library loaded?

### ISSUE THREAD

**Issue by qtwu** [Alex313031/Thorium-Android#65]
**System Details**
 - OS: Android 12
 - Thorium Version 126.0.6478.246

**Problem**
crash when opening 

**Screenshots**
no 

**Additional Notes**
crash log from /data/system/dropbox/ :

Process: org.chromium.thorium
PID: 19619
UID: 10369
Flags: 0x30c83e44
Package: org.chromium.thorium v647824600 (126.0.6478.246)
Foreground: Yes
Process-Runtime: 1274525778
Build: motorola/xpeng_retcn/xpeng:12/S3RXC32.33-8-25/642a3-44a2dd:user/release-keys
Loading-Progress: 1.0

java.lang.UnsatisfiedLinkError: No implementation found for void J.N.MSkFYnu9(long, int, int, int[], int, long) (tried Java_J_N_MSkFYnu9 and Java_J_N_MSkFYnu9__JII_3IIJ) - is the library loaded, e.g. System.loadLibrary?
	at J.N.MSkFYnu9(Native Method)
	at org.chromium.components.safe_browsing.SafeBrowsingApiBridge.startUriLookupBySafeBrowsingApi(chromium-Thorium_Public.apk-stable-647824600:13)
	at vx.run(chromium-Thorium_Public.apk-stable-647824600:515)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by shohabmsk** [comment]
Me also having this problem but not always, sometimes. Sometimes after crashing, I just keep opening and after three or four attempts it opens. Then I don't see the problem for a while. This happening to me randomly few times a day.

**Comment by dnchshrp** [comment]
I have the same issue
